CREATE TABLE roles
(
    id   INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(256) NOT NULL
);
INSERT INTO roles (name)
VALUES ('ROLE_USER');
INSERT INTO roles (name)
VALUES ('ROLE_MODERATOR');
INSERT INTO roles (name)
VALUES ('ROLE_ADMIN');